name: 墨水屏综合看板推送

on:
  schedule:
    - cron: '57 * * * *'   # 避开整点高峰
    - cron: '23 */2 * * *' # 每2小时再跑一次保底
    - cron: '13 0 * * *' # 8:13跑一次
    - cron: '12 1 * * *' # 9:12跑一次
    - cron: '11 2 * * *' # 10:11跑一次
    - cron: '8 3 * * *' # 11:08跑一次
    - cron: '12 4 * * *' # 12:12跑一次
    - cron: '11 5 * * *' # 13:11跑一次
    - cron: '13 6 * * *' # 14:13跑一次
    - cron: '12 7 * * *' # 15:12跑一次
    - cron: '6 8 * * *' # 16:6跑一次
    - cron: '13 9 * * *' # 17:13跑一次
    - cron: '16 10 * * *' # 18:16跑一次
    - cron: '24 11 * * *' # 19:24跑一次
    - cron: '13 12 * * *' # 20:13跑一次
    - cron: '36 13 * * *' # 21:36跑一次
    - cron: '23 14 * * *' # 22:23跑一次
    - cron: '3 15 * * *' # 23:03跑一次
    - cron: '11 16 * * *' # 24:11跑一次

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 获取代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 安装 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 安装依赖包
        run: pip install requests pillow zhdate

      - name: 运行！生成图片并推送
        env:
          ZECTRIX_API_KEY: ${{ secrets.ZECTRIX_API_KEY }}
          ZECTRIX_MAC_1: ${{ secrets.ZECTRIX_MAC_1 }}
          ZECTRIX_MAC_2: ${{ secrets.ZECTRIX_MAC_2 }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AMAP_WEATHER_KEY: ${{ secrets.AMAP_WEATHER_KEY }}
        run: python main.py
